// `.env.ts` is generated by the `npm run env` command
// import env from './.env';
import * as enUS from '../assets/i18n/en-US.json';
import * as trTR from '../assets/i18n/tr-TR.json';

const SUPPORTED_LANGUAGES = [
  {'code': 'en-US', 'name': 'English', 'source': enUS},
  {'code': 'tr-TR', 'name': 'Türk'   , 'source': trTR},
];

export const environment = {
  production: true,
  pwa: false,
  version: "1.0",
  name: "prod",
  defaultLanguage: SUPPORTED_LANGUAGES[0].code,
  supportedLanguages: [
    SUPPORTED_LANGUAGES[0].code,
    SUPPORTED_LANGUAGES[1].code,
  ],
  supportedLanguageObjs: SUPPORTED_LANGUAGES,
  firebase: {
    apiKey: "AIzaSyA66eBE0jgCC58YBWdqb_Em9dhOsWJ0msI",
    authDomain: "rao-vat-miraisoft.firebaseapp.com",
    databaseURL: "https://rao-vat-miraisoft.firebaseio.com",
    projectId: "rao-vat-miraisoft",
    storageBucket: "rao-vat-miraisoft.appspot.com",
    messagingSenderId: "843101426914",
    appId: "1:843101426914:web:b19540c64df2f9cfc73abb",
    measurementId: "G-BJXR586K2V"
  },
  providersSocial: {
    GOOGLE: 'GOOGLE',
    FACEBOOK: 'FACEBOOK'
  },
  apiUrl: 'http://27.72.31.133:6900/api/'

};
